name: "CD"

on:
  push:
    branches: ["main", "release"]
  pull_request:
    branches: ["main", "release"]

jobs:
  tests:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  deploy:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

    #   - name: Setup SSH Azure
    #     env:
    #       SSH_USER: ${{ secrets.AZURE_SSH_USER }}
    #       SSH_HOST: ${{ secrets.AZURE_SSH_HOST_DEV }}
    #       SSH_KEY: ${{ secrets.AZURE_SSH_KEY }}
    #     run: |
    #       mkdir ~/.ssh
    #       echo "$SSH_KEY" > ~/.ssh/id_rsa_gcp
    #       chmod 600 ~/.ssh/id_rsa_gcp
    #       cat >> ~/.ssh/config << END
    #         Host google-cloud
    #         HostName $SSH_HOST
    #         User $SSH_USER
    #         IdentityFile ~/.ssh/id_rsa_gcp
    #         StrictHostKeyChecking no
    #       END

    #   - name: Deploy em Produção
    #     if: github.ref == 'refs/heads/main'
    #     run: ssh google-cloud ./deploy.sh --prod

    #   - name: Deploy em Dev
    #     if: github.ref == 'refs/heads/release'
    #     run: ssh google-cloud ./deploy.sh --release
